### DISCUSSION TITLE
b-pagination customization

### DISCUSSION THREAD

**Discussion by georgesstein** [bootstrap-vue/bootstrap-vue#7120] [Q&A] [answered]
How to customize the styles of the first element, last and ellipsis?
Here is an example:
<img width="763" alt="image" src="https://user-images.githubusercontent.com/60657051/215205255-d767b874-30be-4749-949f-215dac5726f5.png">

**Comment by georgesstein** [comment, marked as answer]
Finally I got it:

```html
<div class="controls">
  <b-pagination
        v-model="filters.page"
        :total-rows="filters.totalCount"
        :per-page="filters.perPage"
        first-number
        last-number
        next-class="last-el"
      >
  </b-pagination>
</div>
```

```scss
.controls::v-deep > .pagination > .page-item.last-el {
  display: flex;
  align-items: center;
  justify-content: center;
  margin-left: 8px;
}

.controls::v-deep > .pagination > .page-item.last-el > .page-link {
  width: 22px;
  height: 22px;
  border-radius: 50%;
  padding: 0;
  color: #212126;
}
```
