### ISSUE TITLE
Scroll body of modal with fixed header?

### ISSUE THREAD

**Issue by DavidRueter** [bootstrap-vue/bootstrap-vue#1344]
Is it possible to do something like this with a long modal, where the header remains fixed while the body of the modal scrolls?  See:  https://github.com/keaukraine/bootstrap4-fs-modal

**Comment by tmorehouse** [comment]
You can sue some custom CSS to target `.modal-body` to restrict the height and set `overflow-y: scroll`

```css
.my-modal .modal-body {
  max-height: 80vh; /* max 80% of the viewport height */
  overflow-y: auto;
}
```

and then set `my-modal` class on b-modal:

```html
<b-modal class="my-modal" title="Foobar">
   Scrollable body with long content
</b-modal>
```
