### ISSUE TITLE
How to create a Full Screen Modal Popup ?

### ISSUE THREAD

**Issue by kamleshkatpara** [bootstrap-vue/bootstrap-vue#1730]
Hi,

I tried to create a full screen modal popup, but not working with custom css.

Please suggest.

**Comment by emanuelmutschlechner** [comment]
@kamleshkatpara 
Try this CSS snippet:
```css
.modal-fullscreen1 .modal {
    padding: 0 !important;
}
.modal-fullscreen1 .modal-dialog {
    max-width: 100%;
    height: 100%;
    margin: 0;
}
.modal-fullscreen1 .modal-content {
    border: 0;
    border-radius: 0;
    min-height: 100%;
    height: auto;
}

.modal-fullscreen2  .modal {
    padding: 0 !important;
}
.modal-fullscreen2 .modal-dialog {
    max-width: 100%;
    height: 100%;
    margin: 0;
}
.modal-fullscreen2 .modal-content {
    width: calc(100% - 2rem);
    min-height: 100%;
    height: auto;
    margin: 1rem;
}
```
```html
<div>
    <b-btn v-b-modal.modal1>Launch demo modal1</b-btn>
    <b-btn v-b-modal.modal2>Launch demo modal2</b-btn>
    <b-modal id="modal1" class="modal-fullscreen1" title="Bootstrap-Vue">
        <p class="my-4">Hello from modal1!</p>
    </b-modal>
    <b-modal id="modal2" class="modal-fullscreen2" title="Bootstrap-Vue">
        <p class="my-4">Hello from modal2!</p>
    </b-modal>
</div>
```
