### ISSUE TITLE
docs page is not optimized for mobile click

### ISSUE THREAD

**Issue by rinick** [bootstrap-vue/bootstrap-vue#1816]
to reproduce
1) open this link on android
https://bootstrap-vue.js.org/docs/components/form-radio
2) click any radio button, there is 300ms delay in the click event

actually 300ms delay is for all click event

this is not expected, since the head has 
`<meta content="width=device-width,initial-scale=1" name="viewport">`

this delay doesn't happen on ios right away, but after some scroll and click, it can happen too

reason:
mobile viewport meta expect the body element contains all the children element. but this page contain some button bar which are bigger than page width, cause it to overflow

solution
1) simply solution
```css
#__nuxt{
  overflow-x: scroll; /* hidden works too but may cause some elements out of screen*/
}
```
2) better solution
apply `overflow-x: scroll` on each item that requires more than 320px width and can't wrap
so user don't see that 30% white area along the whole page when they drag it
