### ISSUE TITLE
Add a collapse class on collapse component

### ISSUE THREAD

**Issue by Soullivaneuh** [bootstrap-vue/bootstrap-vue#2012]
Before using Vue, I was able to put an icon a each collapse link like that:

```scss
a {
  &[data-toggle="collapse"]:not(.btn):not(.no-icon) {
    &::before {
      font-family: FontAwesome, sans-serif;
      content: "\f147";
      color: map_get($project-colors, 'red');
      margin-right: 5px;
    }
    &.collapsed::before,
    &[aria-expanded="false"] {
      content: "\f196";
    }
  }
}
```

But the `data-toggle="collapse"` does not exist anymore. The issue is, I can't revert to `aria-expanded` nor `aria-controls` because they are use for other components too (dropdown for example).

The feature request is quite simple: Add a simple `collapse` class on the component html rendering, or something similar to easily identify it on css.

What do you think?
