### ISSUE TITLE
Bootstrap Table collapsible columns

### ISSUE THREAD

**Issue by rajashekarappala** [bootstrap-vue/bootstrap-vue#2717]
Hi,
I am trying to implement a responsive b-table just like jquery datatables i.e, extra columns should be collapsed like the example below.
https://datatables.net/extensions/responsive/examples/display-control/auto.html
is there a way I can achieve the same with b-table(I don't want to use stacked because it stacks all the columns instead of few extra clomns).

**Comment by jackmu95** [comment]
@rajashekarappala See: https://bootstrap-vue.js.org/docs/components/table#row-details-support

**Comment by rajashekarappala** [comment]
Hi @jackmu95, Thanks for the reply.
It looks similar but what I need is that it should be automatic and collapse according to the screen size. I mean here we are showing row details but they won't be converted as columns if the screen size increases. But I think I should manage that somehow, 
thank you.

**Comment by tmorehouse** [comment]
You can achieve this with basic CSS and CSS media queries.

The following will hide the 2nd column in a table, when the screen is 600px wide or less:

```css
@media only screen and (max-width: 600px) {
  table > thead > tr > :nth-child(2),
  table > tbody > tr > :nth-child(2),
  table > tfoot > tr > :nth-child(2) {
    display: none;
  }
}
```
