### ISSUE TITLE
Sticky headers for bootstrap-vue tables

### ISSUE THREAD

**Issue by lionsarmor** [bootstrap-vue/bootstrap-vue#2777]
I need a way to prevent the table headers from scrolling up with the rest of the table, or just a way to add scroll bars to the table in such a way the header does not move. here is an example.
![2](https://user-images.githubusercontent.com/30090551/53834200-683cd580-3f58-11e9-8a64-7cf7ac8a906d.PNG)
![1](https://user-images.githubusercontent.com/30090551/53834201-683cd580-3f58-11e9-8078-aecea956bc82.PNG)

**Comment by tmorehouse** [comment]
There are a few ways you can do this... and cross browser is not always guaranteed:

create a class, say, `my-table-scroll`{

```css
table.my-table-scroll,
table.my-table-scroll > thead,
table.my-table-scroll > tbody,
table.my-table-scroll > tfoot,
table.my-table-scroll > tbody > tr,
table.my-table-scroll > thead > tr {
  width: 100%;
  display: block
}
table.my-table-scroll > thead,
table.my-table-scroll > tbody,
table.my-table-scroll > tfoot {
  display: block;
  width: 100%;
  overflow-y: scroll;
}
table.my-table-scroll > thead,
table.my-table-scroll > tfoot {
  height: auto;
}
/* these last two rules you will need to tweak on an as needed basis */
table.my-table-scroll > tbody {
  /* set max height for tbody before it scrolls */
  max-height: 200px;
}
table.my-table-scroll > thead > tr > th,
table.my-table-scroll > thead > tr > td,
table.my-table-scroll > tbody > tr > th,
table.my-table-scroll > tbody > tr > td,
table.my-table-scroll > tfoot > tr > th,
table.my-table-scroll > tfoot > tr > td {
  display: inline-block;
  /* you need to explicitly specify the width of the table cells */
  /* either equal, or specify individual widths based on col index. */
  /* Here, we assume you have 4 columns of data */
  width: 25%;
}
/*
  could use sibling selectors to select specific columns for widths:
  td + td (second column)
  td + td + td (3rd column, etc)
*/
```

And then place the class onto your b-table.
