### ISSUE TITLE
<b-table> `_rowVariant` takes priority over `selectVariant`

### ISSUE THREAD

**Issue by Hiws** [bootstrap-vue/bootstrap-vue#3008]
Component: <b-table>

Description:
If you have a selectable table and select a row with a rowVariant you wont be able to see the selectVariant making it bad user experience as the user will not be notified that the row was successfully selected.

The select variant should take priority over the row variant for a better user experience.

**Comment by tmorehouse** [comment]
Another option would be to use a scoped item slot (on a virtual field column) to add an icon show selection state:

```html
<template slot="selected" slot-scope="{ rowSelected }">
  <span v-if="rowSelected" aria-label="selected">
    <b aria-hidden="true">√</b>
  </span>
</template>
```

**Comment by tmorehouse** [comment]
In this case, both variants are being applied to the row, and which ever one was defined last in the Bootstrap V4 SCSS will take precedence.

Another workaround would be to temporarily suppress the `_rowVariant` by setting it to an empty string, and when unselected restore the original `_rowVariant`.

Something else we could look into is providing a different type of feedback to signify that the row is selected (such as a border).

You can also target the selected rows (which have a class `b-table-selected` with custom CSS to define a row background color (applied to the TD's and TH's inside the row), and set `selected-variant` prop to a blank string.  Your custom CSS would be defined after Bootstrap's CSS (typically), and would take precedence over any other variant applied to the row. ie.:

```css
table.b-table-selectable > tbody > tr.b-row-selected > td,
table.b-table-selectable > tbody > tr.b-row-selected > th {
  background-color: cyan;
}
```

**Comment by Hiws** [comment]
Appreciate the workaround. 
Just adding a small typo fix as you were targeting the wrong class on the tr's

`
table.b-table-selectable > tbody > tr.b-table-row-selected > td,
table.b-table-selectable > tbody > tr.b-table-row-selected > th {
  background-color: cyan;
}
`

**Comment by tmorehouse** [comment]
Fixed type typo my example above.

If you want to use bootstrap V4 colors, you can use their CSS `:root` variables:

```css
table.b-table-selectable > tbody > tr.b-table-row-selected > td,
table.b-table-selectable > tbody > tr.b-table-row-selected > th {
  background-color: var(--info);
}
```

The list of the (default) Bootstrap root color variables is:
```css
:root {
    --blue: #007bff;
    --indigo: #6610f2;
    --purple: #6f42c1;
    --pink: #e83e8c;
    --red: #dc3545;
    --orange: #fd7e14;
    --yellow: #ffc107;
    --green: #28a745;
    --teal: #20c997;
    --cyan: #17a2b8;
    --white: #fff;
    --gray: #6c757d;
    --gray-dark: #343a40;
    --primary: #007bff;
    --secondary: #6c757d;
    --success: #28a745;
    --info: #17a2b8;
    --warning: #ffc107;
    --danger: #dc3545;
    --light: #f8f9fa;
    --dark: #343a40;
}
```
