### ISSUE TITLE
Empty row in <b-table> is hoverable

### ISSUE THREAD

**Issue by ipa1981** [bootstrap-vue/bootstrap-vue#3079]
When using both `hover` prop and `empty` slot in <b-table /> the row displaying there are no results is hoverable. It looks a bit unexpected.

Example: https://codepen.io/anon/pen/BEWERe (Just hover on the text "There are no records to show")

A quick fix is just to override CSS somehow like that:

```css
.table-hover tbody tr.b-table-empty-row:hover{ /* dont' make empty row hoverable */
	background-color: inherit;
}
```
