### ISSUE TITLE
Missing modal styles (opacity) since version beta-21

### ISSUE THREAD

**Issue by tristanbes** [bootstrap-vue/bootstrap-vue#3400]
Hello,

In the version .21, it seems that some styles are missing.
The backdrop of the modal is now plain black instead of `opacity.5`

It seems that this rule is no longer present

```css
.modal-backdrop:not(.show):not(.fade) {
    opacity: .5;
}
```
