### ISSUE TITLE
Cannot set shadow on dropdown menu

### ISSUE THREAD

**Issue by sprocket99** [bootstrap-vue/bootstrap-vue#3572]
How do I set a shadow on the drop-down menu?

```
            <b-dropdown size="sm" variant="primary">
              <div class="shadow">...</div>
            </b-dropdown>

  .shadow{
    -webkit-box-shadow: 5px 5px 15px 0px rgba(0,0,0,0.5);
    -moz-box-shadow: 5px 5px 15px 0px rgba(0,0,0,0.5);
    box-shadow: 5px 5px 15px 0px rgba(0,0,0,0.5);
  }
```

I could do this with plain bootstrap :

<div class="dropdown-menu shadow">...</div>

Now the above code sets the shadow on the inner div but not the whole menu. When using F12 I see there is a parent `ul` which wraps my div with class `dropdown-menu` but setting any shadow css on that class has no effect!

![image](https://user-images.githubusercontent.com/52204959/60189806-71b0bd00-9829-11e9-9d48-9d89495d784b.png)

**Comment by tmorehouse** [comment]
Note you shouldn't place anything else in a `b-dropdown` that isn't a supported sub-component (i.e. `<div>` is not supported).

Use targetted CSS:

```css
 .dropdown.shadow .dropdown-menu {
    -webkit-box-shadow: 5px 5px 15px 0px rgba(0,0,0,0.5);
    -moz-box-shadow: 5px 5px 15px 0px rgba(0,0,0,0.5);
    box-shadow: 5px 5px 15px 0px rgba(0,0,0,0.5);
  }
```

```html
<b-dropdown size="sm" variant="primary" class="shadow">
    <b-dropdown-item>...</b-dropdown-item>
    <b-dropdown-item>...</b-dropdown-item>
</b-dropdown>
```

**Comment by sprocket99** [comment]
Thanks for your reply, here is my code, the shadows still do not show:

```
            <b-dropdown size="sm" variant="primary" style="margin-right: 10px;" class="shadow">
              <template slot="button-content">
                <fa-icon class="progress-icon" icon="sync-alt" spin />
                <span>Running Jobs</span>
                <span class="badge badge-light job-count">{{jobs.length}}</span>
              </template>
              <b-dropdown-item class="job" v-for="job in jobs" :key="job.id">
                <div class="title">
                  {{job.description}}
                </div>
                <div class="desc">
                  {{job.progress.description | ellipsis}}
                </div>
                <b-progress :value="job.progress.percentage" variant="success" style="margin-top: 3px; height: 4px;" animated />
              </b-dropdown-item>
            </b-dropdown>

  .dropdown.shadow .dropdown-menu {
    -webkit-box-shadow: 5px 5px 15px 0px rgba(0,0,0,0.5);
    -moz-box-shadow: 5px 5px 15px 0px rgba(0,0,0,0.5);
    box-shadow: 5px 5px 15px 0px rgba(0,0,0,0.5);
  }
```

**Comment by tmorehouse** [comment]
Are you using scoped styles in your app?  scoped styles will not work be default on child custom components.

**Comment by tmorehouse** [comment]
Here is what i get:

![image](https://user-images.githubusercontent.com/2781561/60194780-5b4a3780-9810-11e9-8685-d138c8f2da12.png)


```css
.dropdown.my-shadow .dropdown-menu {
  box-shadow: 5px 5px 15px 0px rgba(0,0,0,0.5);
}
```
