### ISSUE TITLE
Custom carousel control icons

### ISSUE THREAD

**Issue by Anandivdm** [bootstrap-vue/bootstrap-vue#4351]
### Description

I would like to change the carousel control icons (the left and right arrows). I want to replace the current arrows with font awesome icons. The way I am currently doing this is by adding pseudo-elements to the `carousel-control-prev-icon` and `carousel-control-next-icon`.

Unfortunately, I am picking up issues with pseudo-elements in some browsers(Firefox and Edge).

### Request
Is there a way to update the carousel control icons in HTML instead of in CSS?

**Comment by tmorehouse** [comment]
Currently, with Bootstrap v4.3.x, the carousel left/right contols are defined with SCSS/CSS variables and SVG bacgrounds, so it isn't an easy option for us to create a slot for the controls (as all positioning would be lost due to the loss of the needed classes)

You can, however, change the backgound image used via SASS/SCSS variables:

- `$carousel-control-prev-icon-bg`
- `$carousel-control-next-icon-bg`
- `$carousel-control-icon-width`

The default values are:

```scss
$carousel-control-icon-width:        20px !default;
$carousel-control-prev-icon-bg:      url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' fill='#{$carousel-control-color}' width='8' height='8' viewBox='0 0 8 8'><path d='M5.25 0l-4 4 4 4 1.5-1.5L4.25 4l2.5-2.5L5.25 0z'/></svg>") !default;
$carousel-control-next-icon-bg:      url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' fill='#{$carousel-control-color}' width='8' height='8' viewBox='0 0 8 8'><path d='M2.75 0l-1.5 1.5L3.75 4l-2.5 2.5L2.75 8l4-4-4-4z'/></svg>") !default;
```

https://github.com/twbs/bootstrap/blob/0aa6a81c11847b31ce6fc78d00127519247d721e/scss/_variables.scss#L1071-L1095

You would need to copy FontAwesome's SVG for the icons you would like to use.

See https://bootstrap-vue.js.org/docs/reference/theming for details on customizing the variables via SASS/SCSS in your project.
