### ISSUE TITLE
modal-content background-color with variable

### ISSUE THREAD

**Issue by jb-alvarado** [bootstrap-vue/bootstrap-vue#4493]
### Describe the bug
When overriding the `background-color`, of the **modal-content** div, with an variable: `var(--background)` the background become transparent.

### Steps to reproduce the bug
1. Create a variable:
```css
.dark {
  --primary-background: #3b3b3b;
}
 ```
2. apply the variable to the background color:
```css
.modal-content {
  background-color: var(--primary-background);
}
```

### Expected behavior
Adding normal color, like `#ff0000` work perfectly normal. The same behavior should have an variable.

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- nuxt 2.5.1

**Environment:**
- OS: Fedora 31
- Browser: Firefox
- Version: 71

### Demo link
Here is an demo link: https://codesandbox.io/s/smoosh-water-0sywt?fontsize=14&hidenavigation=1&theme=dark
