### ISSUE TITLE
Block level dropdown menu with long dropdown item content

### ISSUE THREAD

**Issue by TheAndroidGuy** [bootstrap-vue/bootstrap-vue#4663]
When using block level dropdown menu with long dropdown item content the dropdown item is not displayed properly.

Here is jsfiddle of the issue: https://jsfiddle.net/aeyr6zgx/

Here is GIF illustrating the problem when using `w-100`:

![primerok](https://user-images.githubusercontent.com/17319245/72860180-5ece7000-3cc6-11ea-81d5-06169be0dc64.gif)

I have some solution but i don't if it is alright.
Instead of `w-100` for the menu class you should use class with `min-width: 100% !important` as shown in the jsfiddle.

Sorry for opening this if it is not considered a bug. I didn't like the way it behaved so i was looking for a solution.

**Comment by tmorehouse** [comment]
The Bootstrap utility class `w-100` class means take 100% of the width of the parent element (`col` in your example).

Ir most cases, it would be used in combination with the `block` prop of `<b-dropdown>` to make the menu the same width as the dropdown button.

**Comment by TheAndroidGuy** [comment]
@tmorehouse But it doesn't always take 100%. `dropdown-menu` has `min-width: 10rem`. I will close this as this is not related to bootstrap-vue.

**Comment by Hiws** [comment]
@tmorehouse 
> Unfortunately Bootstrap v4.4.x doesn't include responsive variations for the `w-100` utility class.

You can create your own if you're using SCSS by utilizing the `map-keys` function and `$grid-breakpoints` map provided by bootstrap.

```scss
@each $breakpoint in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {
    $infix: breakpoint-infix($breakpoint, $grid-breakpoints);
    .w#{$infix}-25 { width: 25%!important;}
    .h#{$infix}-25 { height: 25%!important; }

    .w#{$infix}-50 { width: 50%!important; }
    .h#{$infix}-50 { height: 50%!important; }
    
    .w#{$infix}-75 { width: 75%!important; }
    .h#{$infix}-75 { height: 75%!important; }
   
    .w#{$infix}-100 { width: 100%!important; }
    .h#{$infix}-100 { height: 100%!important; }
  }
}
```
