### ISSUE TITLE
Toast background rendering incorrectly

### ISSUE THREAD

**Issue by aaronfulkerson** [bootstrap-vue/bootstrap-vue#4844]
### Describe the bug

Toasts have darkened backgrounds.

### Steps to reproduce the bug

1. Open a toast.

### Versions

**Libraries:**

- BootstrapVue: 2.5.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Device: PC
- OS: Windows 10 with WSL
- Browser: Edge
- Version: 80

### Demo link

https://imgur.com/a/Pmv8HFR

### Additional context

All I'm doing is calling this.$bvToast.toast()

**Comment by tmorehouse** [comment]
Toasts are opaque be default (meaning they are semi-translucent), and the background of the page will affect this.

It appears you may have some styling that affects the toaster background, making it dark.

Are you importing BootstrapVue's SCSS/CSS _after_ Bootstrap v4.4.x's SCSS/CSS?

**Comment by tmorehouse** [comment]
Toasters (where toasts are rendered) are appended to the `<body>` element by default, and if you have styles that affect the background color of the `<body>` or `<html>` elements, that will affect teh background of the toaster.

**Comment by aaronfulkerson** [comment]
```@import '~bootstrap';
@import '~bootstrap-vue';

html, body {
  height: 100%;
}```

**Comment by tmorehouse** [comment]
Try:

```scss
@import '~bootstrap/scss/bootstrap';
@import '~bootstrap-vue/src/index.scss';

html, body {
  height: 100%;
}
```

or

```scss
@import 'node_modules/bootstrap/scss/bootstrap';
@import 'node_modules/bootstrap-vue/src/index.scss';

html, body {
  height: 100%;
}
```

**Comment by aaronfulkerson** [comment]
Same result.

**Comment by tmorehouse** [comment]
Maybe clear your yar.lock/node_modules?

```sh
rm -r node-modules
rm yarn.lock
yarn install
```

Or remove the CSS:

```scss
html, body {
  height: 100%;
}
```

**Comment by aaronfulkerson** [comment]
Same.

**Comment by tmorehouse** [comment]
Could you make a minimal reproduction that reproduces the issue?  You can emport to JsFiddle, CodePen, or CodeSandbox via the docs playground (https://bootstrap-vue.js.org/play/) as I am unable to reproduce your issue.

**Comment by aaronfulkerson** [comment]
Displays fine in Firefox. This seems like an issue with Edge.

**Comment by aaronfulkerson** [comment]
The issue is also present in Chrome.

**Comment by tmorehouse** [comment]
Perhaps edge defaults the body background to a dark color?

can you inspect the dark background in the inspector to see what class or style is rendering the dark background?

Perhaps you need:

```scss
html, body {
  height: 100%;
 baackground-color: #fff;
}
```
