### ISSUE TITLE
Removing borders from b-avatar (image version)

### ISSUE THREAD

**Issue by wojciech-mocarski** [bootstrap-vue/bootstrap-vue#5154]
### Is your feature request related to a problem? Please describe...

I'd like to use avatars with width=100% without surrounding border.

### Describe the solution you'd like

If there will be property like "no-border" or viariant="none" it will be nice.

### Describe alternatives you've considered

Decorating b-avatar with our own solution.

**Comment by tmorehouse** [comment]
The "border" from image avatars is controlled by CSS (the image width and height are set to `90%`).

This was done to allow the button/link hover styling to show through for the background variant.

You can setup the following CSS to change the image size:

```css
.b-avatar img {
  width: 100%;
  height: 100%;
}
```

or if using scoped styles:

```css
.b-avatar /deep/ img {
  width: 100%;
  height: 100%;
}
```
