### ISSUE TITLE
Table sorting icons do not respect bootstrap theme

### ISSUE THREAD

**Issue by ryleyb** [bootstrap-vue/bootstrap-vue#5548]
### Describe the bug

To be clear, this is not a major bug, just food for thought.  Imagine I make my own bootstrap theme that has all green icons.  My table headers will still have black sorting icons, because they are setup as background-image SVGs.  Images do not pick up the default styles so I have to add special cases for them, which is easy enough using SCSS but for a normal user I feel like that's asking a lot.  
### Versions

**Libraries:**

- BootstrapVue: 2.14.0
- Bootstrap: 4.5.0
- Vue: 2.6.10

### Demo link

Sample with random theme applied: https://codepen.io/ryleyb1/pen/eYJyEQp

In this case I picked a "dark" theme so at least if you applied `dark` to the table the sorters would be white.  But I (the designer) want green (dammit)! ;)

**Comment by Hiws** [comment]
If you're creating theme, I'd say it would be fairly standard to use SCSS. So Changing the color should be fairly easy as you mention.
However, if you're using normal CSS, you will need to do a normal CSS override, by replacing the icon with the same icon of a different color by changing the `fill` and `opacity` info in the SVG info.

```css
.table.b-table > thead > tr > [aria-sort="none"], .table.b-table > tfoot > tr > [aria-sort="none"] {
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='101' height='101' view-box='0 0 101 101' preserveAspectRatio='none'%3e%3cpath fill='%2300bc8c' opacity='1' d='M51 1l25 23 24 22H1l25-22zM51 101l25-23 24-22H1l25 22z'/%3e%3c/svg%3e") 
}

.table.b-table > thead > tr > [aria-sort="ascending"], .table.b-table > tfoot > tr > [aria-sort="ascending"] {
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='101' height='101' view-box='0 0 101 101' preserveAspectRatio='none'%3e%3cpath fill='%2300bc8c' d='M51 1l25 23 24 22H1l25-22z'/%3e%3cpath fill='black' opacity='1' d='M51 101l25-23 24-22H1l25 22z'/%3e%3c/svg%3e");
}

.table.b-table > thead > tr > [aria-sort="descending"], .table.b-table > tfoot > tr > [aria-sort="descending"] {
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='101' height='101' view-box='0 0 101 101' preserveAspectRatio='none'%3e%3cpath fill='black' opacity='1' d='M51 1l25 23 24 22H1l25-22z'/%3e%3cpath fill='%2300bc8c' d='M51 101l25-23 24-22H1l25 22z'/%3e%3c/svg%3e");
}
```

https://codepen.io/Hiws/pen/BajJrzz
