### ISSUE TITLE
Vue transitions don't work when using Badges because of transition property

### ISSUE THREAD

**Issue by mohicandog** [bootstrap-vue/bootstrap-vue#5593]
### Describe the bug

Vue transitions don't work when using Badges because of transition property

### Steps to reproduce the bug

```
        <transition name="fade">
          <p v-if="show" class="badge badge-primary">meow</p>
        </transition>

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.5s;
}
.fade-enter, .fade-leave-to /* .fade-leave-active below version 2.1.8 */ {
  opacity: 0;
}
```

### Expected behavior

Transition should work, without altering default properties

**Comment by Hiws** [comment]
A quick test on the playground seems to work fine.
<https://codepen.io/Hiws/pen/VweqPWw>

Can you provide a reproduction of the issue?

**Comment by mohicandog** [comment]
I couldnt recreate this error in 1 hour of trying, very confusing. But if I turn off .badge transition property on chrome dev tools, it works fine...

**Comment by Hiws** [comment]
One potential issue could be if you're placing the `<transition>` css BEFORE your bootstrap CSS import.

This might cause issue
```scss
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.5s;
}
.fade-enter, .fade-leave-to /* .fade-leave-active below version 2.1.8 */ {
  opacity: 0;
}

@import 'bootstrap.css'
@import 'bootstrap-vue.css'
```

While this shouldn't
```scss
@import 'bootstrap.css'
@import 'bootstrap-vue.css'

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.5s;
}
.fade-enter, .fade-leave-to /* .fade-leave-active below version 2.1.8 */ {
  opacity: 0;
}
```
