### ISSUE TITLE
Stacked and button radio groups should have classes to reflect their custom properties

### ISSUE THREAD

**Issue by Soviut** [bootstrap-vue/bootstrap-vue#5633]
### Is your feature request related to a problem? Please describe...

I wanted to style individual radios in a radio group with the `stacked` prop enabled. However, styling inputs with the `custom-radio` class alone will interfere with normal horizontal radios. It is difficult to create clean selectors that can tell the difference between unstacked, stacked and button radio groups.

### Describe the solution you'd like

Apply a class that indicates if a radio group is normal, stacked or buttons so it's easier to style the child radios.

The output would look like this:
```
<div role="radiogroup" class="radio-group-stacked bv-no-focus-ring" tabindex="-1" id="__BVID__23">
```
I'm not sure if the class naming convention should be `radio-group-stacked` or `custom-radio-group-stacked` to match the `custom-radio` class used on the radios.

### Describe alternatives you've considered

The alternative is to add `class="radio-group-stacked` to all `<b-form-radio-group>` elements.

**Comment by jackmu95** [comment]
While I was about to implement this enhancement and looked up what classes we currently have I came to the conclusion that it is currently possible to do what you want and it would be simply too much to add more custom classes.

```css
/* Style all radios */
.custom-radio {
  font-weight: bold;
}

/* Style inline radios */
.custom-radio.custom-control-inline {
  font-style: italic;
}

/* Style stacked radios */
.custom-radio:not(.custom-control-inline) {
  color: blue;
}

/* Style all radio buttons */
.btn-group-toggle .btn {
  text-transform: uppercase;
}

/* Style inline radio buttons */
.btn-group-toggle:not(.btn-group-vertical) .btn {
  font-style: italic;
}

/* Style stacked radio buttons */
.btn-group-toggle.btn-group-vertical .btn {
  color: blue !important;
}
```

CoseSandbox: https://codesandbox.io/s/bootstrapvue-b-form-radio-group-styling-rjw8e
