### ISSUE TITLE
Card Column Groups -- how to get a fluid display of cards ?

### ISSUE THREAD

**Issue by dosstx** [bootstrap-vue/bootstrap-vue#6032]
### Describe the bug

I am using `<b-card-group columns>` for a "Pinterest/Masonry" style effect for displaying my cards. Works great -- except I can't figure out how to get more than 3 cards to show in a row for a "fluid"-like display. 

Here's what it looks like now:

![image](https://user-images.githubusercontent.com/6342102/98596883-b8c41480-229d-11eb-9fef-36e62fd14ea4.png)

Is there a way I can get more cards to display on the sides so it's not just 3 per row? I see in the docs that this may be a "your mileage may vary" type of effect. If I use fluid container for my template, it will fill the entire viewport with the cards like I needed but the downside is that it still is 3 cards and with enlarged card images, which is what I don't want.

Thanks for any advice or help you can provide.

**Comment by Hiws** [comment]
The `card-column` class is hardcoded to 3 columns when above the `sm` breakpoint.
You can make this more dynamic by defining more/lower `column-count` at various breakpoints.

Here's an example using Bootstrap mixins.
```scss
.card-columns {
    @include media-breakpoint-only(sm) {
        column-count: 2;
    }
    
    @include media-breakpoint-only(md) {
        column-count: 3;
    }

    @include media-breakpoint-only(lg) {
        column-count: 5;
    }

    @include media-breakpoint-only(xl) {
        column-count: 6;
    }
}
```

<https://stackoverflow.com/a/43117538/8397974>
