### ISSUE TITLE
overflow-y tbody, not whole table

### ISSUE THREAD

**Issue by funkyfisch** [bootstrap-vue/bootstrap-vue#6045]
### Is your feature request related to a problem? Please describe...

When creating a fixed-size table with sticky headers, the content is of course overflowed vertically. However, what is actually overflowed is the entire table, not the table body, and the header just happens to stay sticky to give the impression of being fixed. From a design perspective, this does not really make sense, since the scrollable area should denote an area of variable size, and what is actually variable here is the table body, _not_ the entire table (since the header is sticky and static). You are supposed to be scrolling through a list of items of the same scope, and the table header does not belong to that grouping/scope.

Additionally, in the case of ``overflow-y: auto``, since the scrollbar will only appear when the content overflows, the sizing/alignment of the header will change when toggling between a "loading"/"loaded" state of the table (the scrollbar disappears while loading and reappears when content is loaded, pushing the header elements to the left)

### Describe the solution you'd like

I believe that in general when the table itself should be scrollable (that is the intention implied by sticky headers), the y scrollbar should be applied only to the table body by default.
If the headers are not to be sticky, you can simply apply overflow-y to a parent containing the <b-table> element.

### Describe alternatives you've considered

One way to achieve this currently is to apply some convoluted table displays using custom CSS, but it will inevitably break the layouts.

A simplistic approach would be to add a ``margin-top: $table-header-height`` to the scrollbar, but then it still occupies space horizontally in the table header and breaks any applied borders, and will still affect the alignment and distribution of table header elements when it is _not_ overflowing. 

Another way which can achieve a good layout is to not even use a table header, and instead have a custom div "acting" as a table header, such as:
```html
<div id="main">
  <div id="table-with-custom-header">
    <custom-table-header/>
    <b-table/>
  </div>
</div>
```

but this will require at least a proper layout. If you also need sorting support, this will complicate things even more.

Maybe an even better workaround for now would be to use two <b-table>s: one for the header
and one for the body

Here is how it looks today on an example table:

![image](https://user-images.githubusercontent.com/4956573/99082788-e920f100-25c4-11eb-8cbc-59b74895120a.png)

And here is the mentioned desired effect.

![image](https://user-images.githubusercontent.com/4956573/99083451-de1a9080-25c5-11eb-9dc1-2d47cb2d2d06.png)

Example table container vue template:
```html
<div id="request-table-wrapper">
    <b-table
      id="request-table"
      hover
      no-border-collapse
      :items="$store.getters.requestList"
      :fields="fields"
      :sticky-header="`${tableSize}px`"
      :busy="$store.getters.isRequestListLoading"
    >
    <!-- some header and row templates here -->
   </b-table>
</div>
```

Custom table styles:
```css
#request-table-wrapper {
  border-left: 1px solid #dee2e6;
  border-bottom: 1px solid #dee2e6;
  border-right: 1px solid #dee2e6;
}

/*
I had to apply this, for some reason the table has a bottom margin by
default and if I did not, the border would be slightly offset downwards
creating a gap between the lastelement/bottom of scrollbar track and 
the table border. maybe something else to look into too!
*/
#request-table {
  margin-bottom: 0px;
}
```

Global scrollbar styles (theme.scss) :
```scss
::-webkit-scrollbar {
  width: 5px;
}

/* Track */
::-webkit-scrollbar-track {
  background: $gray-200;
  border-radius: 0px;
}

/* Handle */
::-webkit-scrollbar-thumb {
  background: $secondary;
  border-radius: 0px;
}
```

I know this is quite specific, small in impact and very pedantic, but I still wanted to point it out at least from a UI design perspective.
