### ISSUE TITLE
Can we have an attribute for switch style checkbox to allow "untick" showing as "ON"?

### ISSUE THREAD

**Issue by contact-ouyang** [bootstrap-vue/bootstrap-vue#6567]
### Is your feature request related to a problem? Please describe...

The page has a list of items for users to select for calculation. When users enter this page, the page showing all the switches as "ON" as default to include all the items for calculation. Then users can switch the status to "OFF" if he/she wants to exclude certain items for calculation. 
In other words, when the user enter the page, the result array is [ ] but the switch is "ON", when the user click a switch to change the status to "OFF", an item is added to the result array, so the action is opposite to the designed switch. 

### Describe the solution you'd like

If we can have an attribute to switch, something like "reversed-style" then it is much easier to use.

### Describe alternatives you've considered

Currently I put the style below to reverse the style for switch:
```css
    <style scoped>
        .custom-switch {
            padding-left: 3.25rem;
        }
        .custom-switch .custom-control-label:after {
            background-color: #fff;
        }
        .custom-switch .custom-control-label::before {
            left: -3rem;
            width: 1.75rem;
            pointer-events: all;
            border-radius: .5rem;
        }
        .custom-switch .custom-control-input:checked ~ .custom-control-label::after {
            background-color: #bdaead;
            -webkit-transform: translateX(-0.75rem);
            transform: translateX(-0.75rem);
        }
            .custom-control-input:checked ~ .custom-control-label::before {
            background-color: #fff;
            border: 1px solid #adb5bd;
        }
        .custom-control-label:before {
            color: #fff;
            border-color: #007bff;
            background-color: #007bff;
        }
    </style>
```
