### ISSUE TITLE
Toasts not working

### ISSUE THREAD

**Issue by space2pacman** [bootstrap-vue/bootstrap-vue#6764]
this. $bvToast.toast() adds an element to the page, but does not show because of

```css
.toast:not(.show) {
    display: none;
}
```

which is not in the normal bootstrap
