### ISSUE TITLE
轮播图移动速度

### ISSUE THREAD

**Issue by SamSam-oos** [bootstrap-vue/bootstrap-vue#6947]
有什么方法能自定义操控轮播图的移动速度

**Comment by SamSam-oos** [comment]
修改移动速度

**Comment by lichaozhy** [comment]
你可以尝试写一个样式表覆盖以下原来的属性：

```css
.carousel-item {
  position: relative;
  display: none;
  float: left;
  width: 100%;
  margin-right: -100%;
  -webkit-backface-visibility: hidden;
  backface-visibility: hidden;
  transition: -webkit-transform .6s ease-in-out;
  transition: transform .6s ease-in-out; /*.6就是动画速度 */
  transition: transform .6s ease-in-out,-webkit-transform .6s ease-in-out;
```

记得增加一个class或者id来提升定制样式的优先级（以`.slow`为例），只覆盖transition的属性就好：

```css
.carousel-item.slow {
  transition: -webkit-transform 1s ease-in-out;
  transition: transform 1s ease-in-out; /*.6就是动画速度 */
  transition: transform 1s ease-in-out,-webkit-transform 1s ease-in-out;
}
```
