### ISSUE TITLE
Unexpected unknown type selector "disabled" in _avatar.scss

### ISSUE THREAD

**Issue by McLaynV** [bootstrap-vue/bootstrap-vue#7224]
https://github.com/bootstrap-vue/bootstrap-vue/blob/2dee352a52477edcb115ee3bca7d8f824145c750/src/components/avatar/_avatar.scss#L144

The `src/components/avatar/_avatar.scss` file contains
```scss
  a,
  .btn {
    &.b-avatar:hover:not(.disabled):not(disabled) {
      z-index: 1;
    }
  }
```
and `disabled` is not a valid selector in `:not(disabled)`. 

I believe it should be `:not([disabled])` which means "element does not have the `disabled` attribute".
```scss
  a,
  .btn {
    &.b-avatar:hover:not(.disabled):not([disabled]) {
      z-index: 1;
    }
  }
```
